[app]
port = "8085"
jwtkey = "system"


[database]
driver = "PostgreSQL"
db_host = "ec2-54-159-22-90.compute-1.amazonaws.com"
db_user = "pzhvxgmkzwkklf"
db_pass = "79677f0e503409c7efe11cd4402444fbc6d25886136f690df6787b4170279656"
db_name = "dbtlv9se8otn84"
db_port = "5432"



[mailjet]
email = "bens.sky69@gmail.com"
publicKey = "1ccc7215dbdaddb1e70b0ebc1069fed6"
privatekey = "84108b1c5ae4bd0bf33ba15112749f20"

[midtrans]
clientKey = "SB-Mid-client-EA0xRCdwdadMUaf7"
ServerKey = "SB-Mid-server-v2sHF5XNWG7yBDyFo_qOw8HU"
