[app]
port = "8085"
jwtkey = "system"


[database]
driver = "PostgreSQL"
db_host = "localhost"
db_user = "postgres"
db_pass = "arif1412"
db_name = "cps"
db_port = "5432"



[mailjet]
email = "bens.sky69@gmail.com"
publicKey = "1ccc7215dbdaddb1e70b0ebc1069fed6"
privatekey = "84108b1c5ae4bd0bf33ba15112749f20"

[midtrans]
clientKey = "SB-Mid-client-EA0xRCdwdadMUaf7"
ServerKey = "SB-Mid-server-v2sHF5XNWG7yBDyFo_qOw8HU"

[imgbb]
key = "02406488a81ff26d2a22b6306b6b21f9"
